POST http://localhost:8080/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW5lIiwiaWF0IjoxNjc4MzUxNTI1fQ.ChjmIkmOHCGVMYu11PAVRvzgLH1n-QuWpDan3OyjCdA

{
  "content": "테스트입니다."
}